### ISSUE TITLE
1週間以上,脆弱性情報が更新されない場合、こける

### ISSUE THREAD

**Issue by hidekuno** [hidekuno/jvn#69]
```
2020-01-06 10:12:29,948 DEBUG URL = https://jvndb.jvn.jp/myjvn?feed=hnd&method=getVulnOverviewList&rangeDatePublic=n&rangeDatePublished=w&rangeDateFirstPublished=n&startItem=1&maxCountItem=50
Traceback (most recent call last):
  File "/var/local/jvn_db_register.py", line 449, in <module>
    api.download()
  File "/var/local/jvn_db_register.py", line 33, in _
    f(*arg)
  File "/var/local/jvn_db_register.py", line 89, in download
    self.jvn.do_logic(root)
  File "/var/local/jvn_db_register.py", line 164, in do_logic
    identifier    = item.find(self.mod_sec_path('identifier')).text
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by hidekuno** [comment]
検索結果のレコード件数をチェックする
```
<status:Status version="3.3" method="getVulnOverviewList" lang="ja" retCd="0" retMax="50" errCd="" errMsg="" totalRes="0" totalResRet="0" firstRes="1" feed="hnd" rangeDatePublic="n" rangeDatePublished="w" rangeDateFirstPublished="n" startItem="1" maxCountItem="50"/>
```
